project:
  type: website


website:
  title: "Introduction à Python"
  open-graph: true
  favicon: content/.img/favicon.png
  page-navigation: true
  back-to-top-navigation: true
  reader-mode: true
  navbar:
    background: "white"
    search: true
    left:
      - file: index.qmd
        text: Home 
      - sidebar:introduction
      - sidebar:async
      - sidebar:ipc
      - sidebar:conceive
      - sidebar:deploy
      - sidebar:projects
      - sidebar:annexes
    tools:
      - icon: github
        menu:
          - text: Code source
            url:  https://github.com/remigenet/Python-API
  sidebar: 
    - id: home
      title: "Homepage"
      href: index.qmd
    - id: introduction
      title: "Introduction aux API"
      contents:
      - content/Cours_1/1-API101.qmd
      - content/Cours_1/2-User101.qmd
      - content/Cours_1/3-Concepteur101.qmd
      - content/Cours_1/4-guard101.qmd
      - content/Cours_1/5-tester101.qmd
      - content/Cours_1/6-UserApi.qmd
      - section: Travaux Pratiques
        expanded: false
        contents:
        - content/Cours_1/7-TP-Postman_and_coingeko.qmd
      icon: book
    - id: async 
      title: "Consommation avancée d'API"
      contents: 
       - content/Cours_2/1-Protocols.qmd
       - content/Cours_2/2-Authenticate.qmd
       - content/Cours_2/3-Conception-optimizations.py
       - section: Travaux Pratiques
         expanded: false
         contents:
         - content/Cours_2/TP-2-compare-run
    - id: ipc 
      title: "Communication entre Processus (IPC)"
      contents: 
       - content/Cours_3/1-IPC101.qmd
       - content/Cours_3/2-Sockets.qmd
       - content/Cours_3/3-Files.qmd
       - content/Cours_3/4-SharedMemory.qmd
       - content/Cours_3/5-Pipes.qmd
       - content/Cours_3/6-gRPC.qmd
       - content/Cours_3/7-OtherIPCend.qmd
       - section: Travaux Pratiques
         expanded: false
         contents:
         - content/Cours_3/TP-3-1-qmd
         - content/Cours_3/TP-3-2-qmd
    - id: conceive 
      title: "Conception d'APIs"
      contents: 
       - content/Cours_4/1-IntroConception.qmd
       - content/Cours_4/2-Frameworks.qmd
       - content/Cours_4//3-Falsk.qmd
       - content/Cours_4/4-FastAPI.qmd
       - content/Cours_4/5-DjangoRest.qmd
       - content/Cours_4/6-testanddocs.qmd
       - content/Cours_4/7-Good Practice.qmd
       - content/Cours_4/8.Conclusion.qmd
       - section: Travaux Pratiques
         expanded: false
         contents:
         - content/Cours_4/TP-RequetteruneAPI.qmd
    - id: deploy 
      title: "Déploiement d'API - Principes Généraux et Mise en Pratique avec Heroku"
      contents: 
       - content/Cours_5/1-Introdepl.qmd
       - content/Cours_5/2-heroku.qmd
       - content/Cours_5/3-Best Practice.qmd
       - content/Cours_5/4-herodepl.qmd
       - content/Cours_5/5-moreexample.qmd
       - content/Cours_5/6-domain.qmd
       - content/Cours_5/7-end.qmd
    - id: projects 
      title: "Sujets de Projets possibles"
    - id: annexes 
      title: "Annexes"
      contents: 
      - content/Annexes/LinuxTerminal.qmd
      - content/Annexes/git_basics.qmd
      - content/Annexes/git_advanced.qmd
        
  repo-url: https://github.com/remigenet/Python-API
  repo-branch: main
  page-footer:
    left: |
      Introduction à Python, Rémi Genet.<br>
      Licence {{< fa brands creative-commons >}}<br>
      Code source disponible sur [`Github`](https://github.com/remigenet/Python-API)
    right: |
      Site construit avec {{< fa brands python >}} et [`Quarto`](https://quarto.org/)<br>
      Inspiration pour la mise en forme du site [ici](https://github.com/linogaliana/python-datascientist)<br>
      [Code source disponible sur {{< fa brands github >}} `GitHub`](https://github.com/remigenet/Python-API)



format:
  html:
    light: sandstone
    dark: darkly
    css: styles.css
    toc: true
    toc-depth: 3
    code-overflow: wrap

format-links: true
author: Remi Genet
date: today
date-format: iso
page-layout: article
google-scholar: true
commentable: true
validate-yaml: false
crossref:
  chapters: true
lightbox: auto