<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.4.534">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Remi Genet">
<meta name="dcterms.date" content="2024-01-04">
<meta name="description" content="Numpy, Scipy, pour ne cité qu’eux">

<title>Introduction à Python - Calcul Scientifique et Optimization</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
</style>


<script src="../../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../../site_libs/clipboard/clipboard.min.js"></script>
<script src="../../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../../site_libs/quarto-search/fuse.min.js"></script>
<script src="../../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../../">
<link href="../../content/Cours_3/1-IPCwarming.html" rel="prev">
<link href="../../content/.img/favicon.png" rel="icon" type="image/png">
<script src="../../site_libs/quarto-html/quarto.js"></script>
<script src="../../site_libs/quarto-html/popper.min.js"></script>
<script src="../../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../../site_libs/quarto-html/anchor.min.js"></script>
<link href="../../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../../site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../../site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">
<link href="../../site_libs/quarto-contrib/fontawesome6-0.1.0/all.css" rel="stylesheet">
<link href="../../site_libs/quarto-contrib/fontawesome6-0.1.0/latex-fontsize.css" rel="stylesheet">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>


<link rel="stylesheet" href="../../styles.css">
<meta property="og:title" content="Introduction à Python - Calcul Scientifique et Optimization">
<meta property="og:description" content="Numpy, Scipy, pour ne cité qu’eux">
<meta property="og:image" content="https://remigenet.github.io/Python-API/content/Cours_3/.img/numpy.png">
<meta property="og:site_name" content="Introduction à Python">
<meta property="og:image:height" content="166">
<meta property="og:image:width" content="303">
<meta name="citation_title" content="Calcul Scientifique et Optimization">
<meta name="citation_author" content="Remi Genet">
<meta name="citation_publication_date" content="2024-01-04">
<meta name="citation_cover_date" content="2024-01-04">
<meta name="citation_year" content="2024">
<meta name="citation_online_date" content="2024-01-04">
<meta name="citation_fulltext_html_url" content="https://remigenet.github.io/Python-API//content/Cours_3/2-Calcul_Scientifique_et_Optimization.html">
<meta name="citation_language" content="en">
</head>

<body class="nav-sidebar floating nav-fixed">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg " data-bs-theme="dark">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container mx-auto">
    <a class="navbar-brand" href="../../index.html">
    <span class="navbar-title">Introduction à Python</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item">
    <a class="nav-link" href="../../index.html"> 
<span class="menu-text">Home</span></a>
  </li>  
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-introduction-aux-api" role="button" data-bs-toggle="dropdown" aria-expanded="false">
 <span class="menu-text">Introduction aux API</span>
    </a>
    <ul class="dropdown-menu" aria-labelledby="nav-menu-introduction-aux-api">    
        <li>
    <a class="dropdown-item" href="../../content/Cours_1/2-User101.html">
 <span class="dropdown-text">Utiliser une API en tant qu’utilisateur</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../content/Cours_1/3-Concepteur101.html">
 <span class="dropdown-text">Versions et Compilation de Python</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../content/Cours_1/4-guard101.html">
 <span class="dropdown-text">Le PATH</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../content/Cours_1/5-tester101.html">
 <span class="dropdown-text">Path.. et environnements virtuels!</span></a>
  </li>  
        <li><hr class="dropdown-divider"></li>
        <li class="dropdown-header">Travaux Pratiques</li>
    </ul>
  </li>
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-consommation-avancée-dapi" role="button" data-bs-toggle="dropdown" aria-expanded="false">
 <span class="menu-text">Consommation avancée d’API</span>
    </a>
    <ul class="dropdown-menu" aria-labelledby="nav-menu-consommation-avancée-dapi">    
        <li>
    <a class="dropdown-item" href="../../content/Cours_2/1-Protocols.html">
 <span class="dropdown-text">Protocols de communication</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../content/Cours_2/2-Authenticate.html">
 <span class="dropdown-text">Authentification et sécurité des API</span></a>
  </li>  
    </ul>
  </li>
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-communication-entre-processus-(ipc" role="button" data-bs-toggle="dropdown" aria-expanded="false">
 <span class="menu-text">Communication entre Processus (IPC)</span>
    </a>
    <ul class="dropdown-menu" aria-labelledby="nav-menu-communication-entre-processus-(ipc">    
        <li>
    <a class="dropdown-item" href="../../content/Cours_3/1-IPCwarming.html">
 <span class="dropdown-text">Introduction à l’IPC</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../content/Cours_3/2-Calcul_Scientifique_et_Optimization.html">
 <span class="dropdown-text">Calcul Scientifique et Optimization</span></a>
  </li>  
    </ul>
  </li>
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-conception-dapis" role="button" data-bs-toggle="dropdown" aria-expanded="false">
 <span class="menu-text">Conception d’APIs</span>
    </a>
    <ul class="dropdown-menu" aria-labelledby="nav-menu-conception-dapis">    
        <li>
    <a class="dropdown-item" href="../../content/Cours_4/TP-RequetteruneAPI.html">
 <span class="dropdown-text">TP 4 : API d’Indicateurs Financiers avec Gestion des Niveaux d’Accès</span></a>
  </li>  
    </ul>
  </li>
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-déploiement-dapi---principes-généraux-et-mise-en-pratique-avec-heroku" role="button" data-bs-toggle="dropdown" aria-expanded="false">
 <span class="menu-text">Déploiement d’API - Principes Généraux et Mise en Pratique avec Heroku</span>
    </a>
    <ul class="dropdown-menu" aria-labelledby="nav-menu-déploiement-dapi---principes-généraux-et-mise-en-pratique-avec-heroku">    
        <li>
    <a class="dropdown-item" href="../../content/Cours_5/1.html">
 <span class="dropdown-text">L’arbre Syntaxique Abstrait ou AST</span></a>
  </li>  
    </ul>
  </li>
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-sujets-de-projets-possibles" role="button" data-bs-toggle="dropdown" aria-expanded="false">
 <span class="menu-text">Sujets de Projets possibles</span>
    </a>
    <ul class="dropdown-menu" aria-labelledby="nav-menu-sujets-de-projets-possibles">    
    </ul>
  </li>
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-annexes" role="button" data-bs-toggle="dropdown" aria-expanded="false">
 <span class="menu-text">Annexes</span>
    </a>
    <ul class="dropdown-menu" aria-labelledby="nav-menu-annexes">    
        <li>
    <a class="dropdown-item" href="../../content/Annexes/LinuxTerminal.html">
 <span class="dropdown-text">Utiliser le terminal Linux - les bases de bash</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../content/Annexes/git_basics.html">
 <span class="dropdown-text">Git Basics</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../content/Annexes/git_advanced.html">
 <span class="dropdown-text">Git - Pour aller plus loin</span></a>
  </li>  
    </ul>
  </li>
</ul>
          </div> <!-- /navcollapse -->
          <div class="quarto-navbar-tools">
    <div class="dropdown">
      <a href="" title="" id="quarto-navigation-tool-dropdown-0" class="quarto-navigation-tool dropdown-toggle px-1" data-bs-toggle="dropdown" aria-expanded="false" aria-label=""><i class="bi bi-github"></i></a>
      <ul class="dropdown-menu dropdown-menu-end" aria-labelledby="quarto-navigation-tool-dropdown-0">
          <li>
            <a class="dropdown-item quarto-navbar-tools-item" href="https://github.com/remigenet/Python-API">
            Code source
            </a>
          </li>
      </ul>
    </div>
  <a href="" class="quarto-reader-toggle quarto-navigation-tool px-1" onclick="window.quartoToggleReader(); return false;" title="Toggle reader mode">
  <div class="quarto-reader-toggle-btn">
  <i class="bi"></i>
  </div>
</a>
</div>
      </div> <!-- /container-fluid -->
    </nav>
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="../../content/Cours_3/2-Calcul_Scientifique_et_Optimization.html">Calcul Scientifique et Optimization</a></li></ol></nav>
        <a class="flex-grow-1" role="button" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation floating overflow-auto">
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../content/Cours_3/1-IPCwarming.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Introduction à l’IPC</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../content/Cours_3/2-Calcul_Scientifique_et_Optimization.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text">Calcul Scientifique et Optimization</span></a>
  </div>
</li>
        <li class="sidebar-item">
 <span class="menu-text">content/Cours_3/3-MachineLearning.qmd</span>
  </li>
        <li class="sidebar-item">
 <span class="menu-text">content/Cours_3/4-Access_Internet.qmd</span>
  </li>
        <li class="sidebar-item">
 <span class="menu-text">content/Cours_3/5-Feed_Internet.qmd</span>
  </li>
        <li class="sidebar-item">
 <span class="menu-text">content/Cours_3/6-Visualisation.qmd</span>
  </li>
        <li class="sidebar-item">
 <span class="menu-text">content/Cours_3/bonus-pandas_short_examplet.qmd</span>
  </li>
        <li class="sidebar-item">
 <span class="menu-text">content/Cours_3/TP-pandas_and_geography.ipynb</span>
  </li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#calcul-scientifique-et-optimization" id="toc-calcul-scientifique-et-optimization" class="nav-link active" data-scroll-target="#calcul-scientifique-et-optimization">Calcul Scientifique et Optimization</a></li>
  <li><a href="#ii.-sockets" id="toc-ii.-sockets" class="nav-link" data-scroll-target="#ii.-sockets">II. Sockets</a>
  <ul class="collapse">
  <li><a href="#définition-et-principes-de-base-des-sockets" id="toc-définition-et-principes-de-base-des-sockets" class="nav-link" data-scroll-target="#définition-et-principes-de-base-des-sockets">1. Définition et Principes de Base des Sockets</a></li>
  <li><a href="#types-de-sockets-stream-vs-datagram" id="toc-types-de-sockets-stream-vs-datagram" class="nav-link" data-scroll-target="#types-de-sockets-stream-vs-datagram">2. Types de Sockets : Stream vs Datagram</a></li>
  <li><a href="#sockets-en-réseau-tcpip-et-udp" id="toc-sockets-en-réseau-tcpip-et-udp" class="nav-link" data-scroll-target="#sockets-en-réseau-tcpip-et-udp">3. Sockets en Réseau : TCP/IP et UDP</a></li>
  <li><a href="#fonctionnement-des-sockets" id="toc-fonctionnement-des-sockets" class="nav-link" data-scroll-target="#fonctionnement-des-sockets">4. Fonctionnement des Sockets</a></li>
  <li><a href="#exemple-de-communication-socket-en-python" id="toc-exemple-de-communication-socket-en-python" class="nav-link" data-scroll-target="#exemple-de-communication-socket-en-python">5. Exemple de Communication Socket en Python</a></li>
  </ul></li>
  <li><a href="#création-dun-socket-tcpip" id="toc-création-dun-socket-tcpip" class="nav-link" data-scroll-target="#création-dun-socket-tcpip">Création d’un socket TCP/IP</a>
  <ul class="collapse">
  <li><a href="#gérer-et-différencier-plusieurs-clients-en-python" id="toc-gérer-et-différencier-plusieurs-clients-en-python" class="nav-link" data-scroll-target="#gérer-et-différencier-plusieurs-clients-en-python">6. Gérer et Différencier Plusieurs Clients en python</a>
  <ul class="collapse">
  <li><a href="#a.-exemple-plus-complet" id="toc-a.-exemple-plus-complet" class="nav-link" data-scroll-target="#a.-exemple-plus-complet">a. Exemple plus complet</a></li>
  <li><a href="#b.-exemple-avec-une-api-http" id="toc-b.-exemple-avec-une-api-http" class="nav-link" data-scroll-target="#b.-exemple-avec-une-api-http">b. Exemple avec une API HTTP</a></li>
  </ul></li>
  </ul></li>
  </ul>
<div class="quarto-code-links"><h2>Code Links</h2><ul><li><a href="https://mybinder.org/v2/gh/remigenet/Python-API/HEAD?urlpath=vscode" target="_blank"><i class="bi bi-journals"></i>Launch Binder</a></li></ul></div></nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Calcul Scientifique et Optimization</h1>
  <div class="quarto-categories">
    <div class="quarto-category">Cours</div>
    <div class="quarto-category">Fondamentaux</div>
  </div>
  </div>

<div>
  <div class="description">
    Numpy, Scipy, pour ne cité qu’eux
  </div>
</div>


<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>Remi Genet </p>
          </div>
  </div>
    
    <div>
    <div class="quarto-title-meta-heading">Published</div>
    <div class="quarto-title-meta-contents">
      <p class="date">2024-01-04</p>
    </div>
  </div>
  
    
  </div>
  


</header>


<section id="calcul-scientifique-et-optimization" class="level1">
<h1>Calcul Scientifique et Optimization</h1>
<hr>
</section>
<section id="ii.-sockets" class="level1">
<h1>II. Sockets</h1>
<pre><code>Les sockets constituent l'une des méthodes d'IPC les plus directes et les plus répandues, en particulier pour la communication réseau. Les sockets sont des points de terminaison pour envoyer et recevoir des données entre des processus, soit sur le même ordinateur, soit sur des ordinateurs différents connectés par un réseau. Ils sont essentiels pour la communication réseau et sont utilisés par de nombreux protocoles de communication.</code></pre>
<section id="définition-et-principes-de-base-des-sockets" class="level2">
<h2 class="anchored" data-anchor-id="définition-et-principes-de-base-des-sockets">1. Définition et Principes de Base des Sockets</h2>
<pre><code>Un socket est associé à un port spécifique sur un hôte, permettant aux applications de s'adresser à un service spécifique sur un ordinateur dans un réseau. Les sockets sont essentiels pour établir une communication client-serveur et sont utilisés par de nombreuses API pour gérer les requêtes et les réponses.</code></pre>
</section>
<section id="types-de-sockets-stream-vs-datagram" class="level2">
<h2 class="anchored" data-anchor-id="types-de-sockets-stream-vs-datagram">2. Types de Sockets : Stream vs Datagram</h2>
<pre><code>Il existe deux types principaux de sockets : les sockets de flux (stream sockets) et les sockets de datagramme (datagram sockets). Les sockets de flux utilisent le protocole TCP (Transmission Control Protocol) pour une communication orientée connexion, garantissant que les données arrivent dans l'ordre et sans erreur. Les sockets de datagramme, en utilisant UDP (User Datagram Protocol), sont orientés non-connexion et ne garantissent pas l'ordre ou la fiabilité des paquets.</code></pre>
</section>
<section id="sockets-en-réseau-tcpip-et-udp" class="level2">
<h2 class="anchored" data-anchor-id="sockets-en-réseau-tcpip-et-udp">3. Sockets en Réseau : TCP/IP et UDP</h2>
<pre><code>Les sockets TCP/IP sont largement utilisés pour les communications fiables et ordonnées, tandis que les sockets UDP sont utilisés pour des communications plus rapides mais potentiellement moins fiables. Le choix entre TCP et UDP dépend des exigences de l'application en termes de fiabilité, d'ordre et de performance.</code></pre>
</section>
<section id="fonctionnement-des-sockets" class="level2">
<h2 class="anchored" data-anchor-id="fonctionnement-des-sockets">4. Fonctionnement des Sockets</h2>
<ol type="1">
<li><code>Création d'un Socket : Un socket est créé en spécifiant un type de communication (TCP ou UDP, par exemple) et une adresse (IP et port).</code></li>
<li><code>Écoute et Connexion : Un serveur écoute sur un port spécifique, tandis qu'un client se connecte à ce port. Pour TCP, le serveur doit accepter la connexion.</code></li>
<li><code>Échange de Données : Une fois la connexion établie, les données peuvent être envoyées et reçues. Les données envoyées à travers un socket doivent être sérialisées (converties en un format pouvant être transmis sur le réseau) et désérialisées à l'autre bout.</code></li>
<li><code>Fermeture du Socket : Après la communication, les sockets doivent être fermés proprement pour libérer les ressources réseau.</code></li>
</ol>
<pre><code>Sérialisation des Objets

La sérialisation est le processus de transformation d'un objet en un format qui peut être facilement stocké ou transmis. En Python, les objets peuvent être sérialisés en utilisant des modules comme pickle, qui permet de convertir un objet en une chaîne de bytes, ou json, pour une représentation en texte qui est également lisible par l'homme et interopérable avec d'autres langages.</code></pre>
</section>
<section id="exemple-de-communication-socket-en-python" class="level2">
<h2 class="anchored" data-anchor-id="exemple-de-communication-socket-en-python">5. Exemple de Communication Socket en Python</h2>
<pre><code>Voici un exemple simple de communication entre un serveur et un client en utilisant les sockets TCP en Python.

Serveur (serveur.py)


</code></pre>
<p>import socket</p>
</section>
</section>
<section id="création-dun-socket-tcpip" class="level1">
<h1>Création d’un socket TCP/IP</h1>
<p>with socket.socket(socket.AF_INET, socket.SOCK_STREAM) as s: # Associe le socket à l’adresse du serveur et écoute les connexions entrantes s.bind((‘localhost’, 6789)) s.listen()</p>
<pre><code>print("Le serveur écoute à l'adresse 'localhost' sur le port 6789")

# Accepte une connexion
conn, addr = s.accept()
with conn:
    print(f"Connecté à {addr}")
    while True:
        data = conn.recv(1024)
        if not data:
            break
        conn.sendall(data)</code></pre>
<pre><code>

</code></pre>
<p>Client (client.py)</p>
<pre><code>import socket

# Création d'un socket TCP/IP
with socket.socket(socket.AF_INET, socket.SOCK_STREAM) as s:
    # Connexion au serveur
    s.connect(('localhost', 6789))

    # Envoi de données
    s.sendall(b'Hello, server')

    # Réception de la réponse
    data = s.recv(1024)
    print(f"Reçu {data!r}")</code></pre>
<pre><code>Dans cet exemple, le serveur écoute sur le port 6789 et attend une connexion. Le client se connecte au serveur et envoie un message "Hello, server". Le serveur reçoit ce message, l'échoit (le renvoie au client), et le client imprime la réponse. C'est un exemple de base de l'échange de données en utilisant les sockets TCP en Python.

Dans les exemples de code fournis pour le serveur et le client, plusieurs éléments clés définissent le fonctionnement des sockets en Python. Voici une explication détaillée de chaque partie :

Serveur (serveur.py)


</code></pre>
<p>import socket</p>
<pre><code>



* `import socket : Importe le module Python socket qui fournit les méthodes et les classes pour la communication réseau.`

    ```
with socket.socket(socket.AF_INET, socket.SOCK_STREAM) as s:</code></pre>
<ul>
<li><p><code>socket.socket : Crée un nouvel objet socket.</code></p></li>
<li><p><code>socket.AF_INET : Spécifie la famille d'adresses, AF_INET pour IPv4.</code></p></li>
<li><p><code>socket.SOCK_STREAM : Spécifie le type de socket, SOCK_STREAM pour le protocole TCP, qui est orienté connexion.</code></p>
<pre><code>s.bind(('localhost', 6789))</code></pre></li>
<li><p><code>s.bind : Associe le socket à une adresse spécifique et à un port. Ici, 'localhost' indique que le serveur écoute sur l'interface réseau locale.</code></p>
<pre><code>s.listen()</code></pre></li>
<li><p><code>s.listen : Met le socket en mode écoute pour accepter les connexions entrantes. Sans argument, il utilise une file d'attente de taille raisonnable par défaut.</code></p>
<pre><code>conn, addr = s.accept()</code></pre></li>
<li><p><code>s.accept : Bloque et attend une connexion entrante. Quand un client se connecte, il retourne un nouveau socket conn représentant la connexion et l'adresse addr du client connecté.</code></p>
<pre><code>data = conn.recv(1024)</code></pre></li>
<li><p><code>conn.recv : Reçoit les données du client. Le nombre 1024 spécifie la taille maximale des données pouvant être reçues à la fois (en octets).</code></p>
<pre><code>conn.sendall(data)</code></pre></li>
<li><p><code>conn.sendall : Envoie les données reçues en retour au client. Cette méthode s'assure que toutes les données sont envoyées.</code></p></li>
</ul>
<pre><code>Client (client.py)


</code></pre>
<p>s.connect((‘localhost’, 6789))</p>
<pre><code>



* `s.connect : Établit une connexion avec le serveur. L'argument est un tuple contenant l'adresse du serveur et le numéro de port.`

    ```
s.sendall(b'Hello, server')</code></pre>
<ul>
<li><p><code>s.sendall : Envoie des données au serveur. Les données sont préfixées par b pour indiquer qu'il s'agit d'un objet bytes, nécessaire pour l'envoi sur le réseau.</code></p>
<pre><code>data = s.recv(1024)</code></pre></li>
<li><p><code>s.recv : Reçoit la réponse du serveur. Encore une fois, 1024 est la taille maximale du bloc de données à recevoir.</code></p></li>
</ul>
<pre><code>Dans ces exemples, le serveur et le client utilisent TCP, un protocole de communication fiable et orienté connexion. Le serveur attend passivement une connexion client, tandis que le client initie activement la connexion. Une fois la connexion établie, ils peuvent communiquer en envoyant et en recevant des données.</code></pre>
<section id="gérer-et-différencier-plusieurs-clients-en-python" class="level2">
<h2 class="anchored" data-anchor-id="gérer-et-différencier-plusieurs-clients-en-python">6. Gérer et Différencier Plusieurs Clients en python</h2>
<pre><code>Un serveur TCP peut gérer plusieurs clients simultanément en utilisant le multithreading ou l'asynchronisme. Lorsqu'un client se connecte et que le serveur accepte la connexion, il crée généralement un nouveau thread ou un processus pour gérer la communication avec ce client. Cela permet au serveur principal de continuer à écouter d'autres clients potentiels. Chaque thread gère un socket de connexion distinct, ce qui permet de différencier les clients.

Voici un exemple simplifié de la façon dont un serveur peut gérer plusieurs clients en utilisant le multithreading en Python :


</code></pre>
<p>import socket import threading</p>
<p>def handle_client(conn, addr): print(f”Connecté à {addr}“) try: while True: data = conn.recv(1024) if not data: break conn.sendall(data) finally: conn.close()</p>
<p>def server(): with socket.socket(socket.AF_INET, socket.SOCK_STREAM) as s: s.bind((‘localhost’, 6789)) s.listen() while True: conn, addr = s.accept() client_thread = threading.Thread(target=handle_client, args=(conn, addr)) client_thread.start()</p>
<p>if <strong>name</strong> == ‘<strong>main</strong>’: server()</p>
<pre><code>

</code></pre>
<p>Dans cet exemple, chaque fois qu’un client se connecte, le serveur crée un nouveau thread qui exécute la fonction handle_client, qui gère la communication avec ce client.</p>
<p>Utiliser une Socket sur un Réseau</p>
<p>Pour utiliser une socket sur un réseau et pas uniquement en local, vous devez lier votre socket à une adresse IP publique ou à une adresse IP locale accessible sur le réseau. Au lieu de lier votre socket à ‘localhost’, vous lieriez à l’adresse IP de l’interface réseau que vous souhaitez utiliser. Assurez-vous que les pare-feu et les routeurs sont configurés pour permettre le trafic sur le port que vous utilisez.</p>
<p>Autres Paramètres pour les Sockets</p>
<pre><code>


* `socket.AF_INET : Utilisé pour IPv4. Pour IPv6, vous utiliseriez socket.AF_INET6.`
* `socket.SOCK_STREAM : Utilisé pour les protocoles orientés connexion comme TCP. Pour les protocoles sans connexion comme UDP, vous utiliseriez socket.SOCK_DGRAM.`

</code></pre>
<p>Cas d’Usage :</p>
<pre><code>


* `socket.SOCK_STREAM : Idéal pour les applications nécessitant une connexion fiable, comme les transferts de fichiers, les communications client-serveur où l'ordre et l'intégrité des données sont importants.`
* `socket.SOCK_DGRAM : Utilisé pour les applications où la rapidité est plus critique que la fiabilité, comme les jeux en temps réel ou la diffusion de vidéos en streaming, où la perte de quelques paquets n'est pas critique.`
* `socket.AF_INET6 : Utilisé pour les applications qui doivent communiquer sur des réseaux IPv6, qui est la dernière version du protocole Internet et supporte un plus grand nombre d'adresses IP.`

</code></pre>
<p>En choisissant le bon type de socket et la bonne famille d’adresses, vous pouvez optimiser votre application pour le réseau et les exigences de communication spécifiques.</p>
<pre><code>


## 7. Différenciation des Messages de Plusieurs Clients en général

</code></pre>
<p>Lorsqu’un serveur TCP reçoit des connexions de plusieurs clients sur le même port, chaque connexion est unique et est représentée par un nouveau socket de connexion. Voici comment cela fonctionne :</p>
<pre><code>


1. `Socket d'Écoute : Le serveur a un "socket d'écoute" qui est lié à une adresse IP spécifique et à un numéro de port. Ce socket écoute les tentatives de connexion entrantes.`
2. `Établissement de la Connexion : Lorsqu'un client tente de se connecter au serveur, le protocole TCP du serveur négocie une connexion avec le protocole TCP du client. Si la négociation réussit, le serveur accepte la connexion.`
3. `Socket de Connexion : Une fois la connexion acceptée, le serveur crée un nouveau "socket de connexion" pour communiquer avec ce client. Ce socket de connexion a une paire d'adresses IP et de ports unique : l'adresse IP et le port du client, et l'adresse IP et le port du serveur. Cette paire unique permet au serveur de différencier les connexions clients, même si toutes les connexions utilisent le même port du serveur.`
4. `Communication : Le serveur communique avec chaque client via son socket de connexion dédié. Même si les données de différents clients arrivent sur le même port d'écoute, elles sont routées vers le socket de connexion approprié grâce à cette paire d'adresses et de ports unique.`

</code></pre>
<p>Définition d’un Port</p>
<p>Un port est un point de terminaison de communication dans le système d’exploitation d’un ordinateur. Les ports sont utilisés par les protocoles de la couche de transport, comme TCP et UDP, pour aider à acheminer les données de l’Internet vers le bon programme sur un ordinateur. Chaque connexion TCP ou UDP est identifiée de manière unique par une paire d’adresses IP et de ports : l’adresse IP et le port de l’expéditeur, et l’adresse IP et le port du destinataire.</p>
<p>Les ports vont de 0 à 65535. Les ports bien connus (de 0 à 1023) sont attribués par l’IANA pour des services spécifiques (par exemple, le port 80 pour le trafic HTTP). Les ports enregistrés (de 1024 à 49151) sont destinés à des applications spécifiques, et les ports dynamiques ou privés (de 49152 à 65535) sont utilisés par les applications pour les connexions temporaires.</p>
<p>En résumé, un port sert de porte d’entrée pour les communications réseau, permettant au système d’exploitation de savoir à quel programme livrer les paquets de données reçus.</p>
<pre><code>


## 8. Avantages et Limitations des Sockets

</code></pre>
<p>Les sockets sont extrêmement polyvalents et permettent une communication en temps réel entre les processus. Cependant, ils peuvent être complexes à gérer correctement, en particulier en ce qui concerne la gestion des erreurs et la synchronisation des communications.</p>
<section id="a.-exemple-plus-complet" class="level3">
<h3 class="anchored" data-anchor-id="a.-exemple-plus-complet">a. Exemple plus complet</h3>
<p>Dans le contexte d’une API, les sockets peuvent être utilisés pour créer un serveur qui écoute les requêtes des clients et y répond. Voici un exemple concret d’un serveur d’API simple utilisant les sockets en Python. Cet exemple illustre un serveur qui accepte des requêtes JSON, traite une action simple (comme une addition), et renvoie une réponse JSON.</p>
<p>Serveur d’API (api_server.py)</p>
<pre><code>import socket
import json
import threading

def process_request(request_data):
    # Simule le traitement d'une requête, ici une simple addition
    data = json.loads(request_data)
    result = data['number1'] + data['number2']
    return json.dumps({'result': result})

def handle_client(conn, addr):
    print(f"Connecté à {addr}")
    try:
        while True:
            data = conn.recv(1024)
            if not data:
                break
            
            # Traite la requête et envoie la réponse
            response = process_request(data.decode('utf-8'))
            conn.sendall(response.encode('utf-8'))
    finally:
        conn.close()

def server():
    with socket.socket(socket.AF_INET, socket.SOCK_STREAM) as s:
        s.bind(('localhost', 6789))
        s.listen()
        print("Serveur d'API démarré sur le port 6789...")
        while True:
            conn, addr = s.accept()
            client_thread = threading.Thread(target=handle_client, args=(conn, addr))
            client_thread.start()

if __name__ == '__main__':
    server()</code></pre>
<pre><code>Client (api_client.py)


</code></pre>
<p>import socket import json</p>
<p>def send_request(number1, number2): request_data = json.dumps({‘number1’: number1, ‘number2’: number2}) with socket.socket(socket.AF_INET, socket.SOCK_STREAM) as s: s.connect((‘localhost’, 6789)) s.sendall(request_data.encode(‘utf-8’)) response = s.recv(1024) print(f”Réponse reçue: {response.decode(‘utf-8’)}“)</p>
<p>if <strong>name</strong> == ‘<strong>main</strong>’: # Envoie une requête d’addition au serveur d’API send_request(10, 20)</p>
<pre><code>

</code></pre>
<p>Explication de l’Exemple :</p>
<pre><code>


* `Le serveur d'API (api_server.py) écoute les connexions entrantes sur le port 6789.`
* `Lorsqu'un client se connecte et envoie une requête, le serveur crée un nouveau thread pour gérer la requête.`
* `La fonction process_request prend les données de la requête, les décode de JSON, effectue une opération (dans cet exemple, une addition), et renvoie le résultat encodé en JSON.`
* `Le client (api_client.py) envoie une requête JSON contenant deux nombres au serveur et attend la réponse.`
* `Lorsque le serveur reçoit la requête, il renvoie le résultat de l'addition sous forme de réponse JSON.`

</code></pre>
</section>
<section id="b.-exemple-avec-une-api-http" class="level3">
<h3 class="anchored" data-anchor-id="b.-exemple-avec-une-api-http">b. Exemple avec une API HTTP</h3>
<p>Dans une architecture d’API classique, il est courant d’avoir un serveur HTTP qui reçoit des requêtes de clients et qui, pour traiter ces requêtes, doit communiquer avec d’autres services ou processus en arrière-plan. Ces services en arrière-plan peuvent être des bases de données, des services de calcul, des systèmes de files d’attente, etc. Les sockets peuvent être utilisés pour cette communication interprocessus (IPC) en arrière-plan.</p>
<p>Voici un exemple où une API HTTP reçoit des requêtes pour effectuer des opérations, et ces opérations sont déléguées à un processus en arrière-plan via un socket. Le serveur HTTP agit comme un frontal, tandis que le processus en arrière-plan effectue le traitement réel et renvoie le résultat au serveur HTTP, qui le transmet ensuite au client.</p>
<p>Serveur HTTP (http_server.py)</p>
<pre><code>from http.server import BaseHTTPRequestHandler, HTTPServer
import json
import socket

class RequestHandler(BaseHTTPRequestHandler):
    def do_POST(self):
        content_length = int(self.headers['Content-Length'])
        post_data = self.rfile.read(content_length)
        response = self.send_to_worker(post_data)
        
        self.send_response(200)
        self.send_header('Content-type', 'application/json')
        self.end_headers()
        self.wfile.write(response)

    def send_to_worker(self, data):
        with socket.socket(socket.AF_INET, socket.SOCK_STREAM) as s:
            s.connect(('localhost', 6790))
            s.sendall(data)
            response = s.recv(1024)
            return response

if __name__ == '__main__':
    server = HTTPServer(('localhost', 6789), RequestHandler)
    print('Starting server at http://localhost:6789')
    server.serve_forever()</code></pre>
<pre><code>Processus de Travail (worker.py)


</code></pre>
<p>import socket import json</p>
<p>def process_data(data): # Simule un traitement de données complexe result = sum(data) return json.dumps({‘result’: result}).encode(‘utf-8’)</p>
<p>def worker(): with socket.socket(socket.AF_INET, socket.SOCK_STREAM) as s: s.bind((‘localhost’, 6790)) s.listen() print(“Worker en écoute sur le port 6790…”) while True: conn, addr = s.accept() with conn: data = conn.recv(1024) response = process_data(json.loads(data)) conn.sendall(response)</p>
<p>if <strong>name</strong> == ‘<strong>main</strong>’: worker()</p>
<pre><code>

</code></pre>
<p>Explication de l’Exemple :</p>
<pre><code>


* `Le serveur HTTP (http_server.py) écoute sur le port 6789 pour les requêtes HTTP POST.`
* `Lorsqu'une requête est reçue, le serveur extrait les données et les envoie au processus de travail via un socket TCP.`
* `Le processus de travail (worker.py) écoute sur le port 6790 pour les connexions du serveur HTTP.`
* `Lorsque le processus de travail reçoit des données, il les traite (dans cet exemple, il calcule la somme d'une liste de nombres) et renvoie le résultat au serveur HTTP.`
* `Le serveur HTTP reçoit la réponse du processus de travail et la renvoie au client HTTP.`

</code></pre>
<p>Dans cet exemple, le serveur HTTP et le processus de travail communiquent sur le réseau local, mais ils pourraient tout aussi bien être sur des machines distinctes. Cela illustre comment les sockets peuvent être utilisés pour la communication interprocessus derrière une façade HTTP, permettant une séparation des préoccupations et la possibilité de distribuer le traitement sur plusieurs processus ou serveurs. ```</p>


</section>
</section>
</section>

<a onclick="window.scrollTo(0, 0); return false;" role="button" id="quarto-back-to-top"><i class="bi bi-arrow-up"></i> Back to top</a></main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    text: function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      return note.innerHTML;
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
<nav class="page-navigation">
  <div class="nav-page nav-page-previous">
      <a href="../../content/Cours_3/1-IPCwarming.html" class="pagination-link  aria-label=" introduction="" à="" l&#39;ipc"="">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text">Introduction à l’IPC</span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
  </div>
</nav>
</div> <!-- /content -->
<footer class="footer">
  <div class="nav-footer">
    <div class="nav-footer-left">
<p>Introduction à Python, Rémi Genet.<br> Licence <i class="fa-brands fa-creative-commons" aria-label="creative-commons"></i><br> Code source disponible sur <a href="https://github.com/remigenet/Python-API"><code>Github</code></a></p>
</div>   
    <div class="nav-footer-center">
      &nbsp;
    </div>
    <div class="nav-footer-right">
<p>Site construit avec <i class="fa-brands fa-python" aria-label="python"></i> et <a href="https://quarto.org/"><code>Quarto</code></a><br> Inspiration pour la mise en forme du site <a href="https://github.com/linogaliana/python-datascientist">ici</a><br> <a href="https://github.com/remigenet/Python-API">Code source disponible sur <i class="fa-brands fa-github" aria-label="github"></i> <code>GitHub</code></a></p>
</div>
  </div>
</footer>




</body></html>